In [3]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv(r"C:\Users\kandl\Downloads\archive (7)\netflix_movies_detailed_up_to_2025.csv")
print(df.shape)
df.head()

(16000, 18)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,language,description,popularity,vote_count,vote_average,budget,revenue
0,10192,Movie,Shrek Forever After,Mike Mitchell,"Mike Myers, Eddie Murphy, Cameron Diaz, Antoni...",United States of America,2010-05-16,2010,6.380,NaN,"Comedy, Adventure, Fantasy, Animation, Family",en,A bored and domesticated Shrek pacts with deal...,203.893,7449,6.380,165000000,752600867
1,27205,Movie,Inception,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ken W...","United Kingdom, United States of America",2010-07-15,2010,8.369,NaN,"Action, Science Fiction, Adventure",en,"Cobb, a skilled thief who commits corporate es...",156.242,37119,8.369,160000000,839030630
2,12444,Movie,Harry Potter and the Deathly Hallows: Part 1,David Yates,"Daniel Radcliffe, Emma Watson, Rupert Grint, T...","United Kingdom, United States of America",2010-11-17,2010,7.744,NaN,"Adventure, Fantasy",en,"Harry, Ron and Hermione walk away from their l...",121.191,19327,7.744,250000000,954305868
3,38757,Movie,Tangled,"Byron Howard, Nathan Greno","Mandy Moore, Zachary Levi, Donna Murphy, Ron P...",United States of America,2010-11-24,2010,7.600,NaN,"Animation, Family, Adventure",en,"Feisty teenager Rapunzel, who has long and mag...",111.762,11638,7.600,260000000,592461732
4,10191,Movie,How to Train Your Dragon,"Chris Sanders, Dean DeBlois","Jay Baruchel, Gerard Butler, Craig Ferguson, A...",United States of America,2010-03-18,2010,7.800,NaN,"Fantasy, Adventure, Animation, Family",en,As the son of a Viking leader on the cusp of m...,110.044,13259,7.800,165000000,494879471

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16000 entries, 0 to 15999
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       16000 non-null  int64
 1   type          16000 non-null  object
 2   title         16000 non-null  object
 3   director      15868 non-null  object
 4   cast          15796 non-null  object
 5   country       15534 non-null  object
 6   date_added    16000 non-null  object
 7   release_year  16000 non-null  int64
 8   rating        16000 non-null  float64
 9   duration      0 non-null      float64
 10  genres        15893 non-null  object
 11  language      16000 non-null  object
 12  description   15868 non-null  object
 13  popularity    16000 non-null  float64
 14  vote_count    16000 non-null  int64
 15  vote_average  16000 non-null  float64
 16  budget        16000 non-null  int64
 17  revenue       16000 non-null  int64
dtypes: float64(4), int64(5), object(9)
memory usage: 2.2+ MB

In [9]:
df.isnull().sum()

show_id             0
type                0
title               0
director          132
cast              204
country           466
date_added          0
release_year        0
rating              0
duration        16000
genres            107
language            0
description       132
popularity          0
vote_count          0
vote_average        0
budget              0
revenue             0
dtype: int64

In [11]:
# Missing values count and percentage

missing_summary = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": round((df.isnull().sum() / len(df)) * 100, 2)
})

missing_summary = missing_summary[missing_summary["Missing Values"] > 0]

missing_summary.sort_values(by="Percentage", ascending=False)

             Missing Values  Percentage
duration              16000      100.00
country                 466        2.91
cast                    204        1.27
director                132        0.82
description             132        0.82
genres                  107        0.67

In [13]:
df.drop(columns=["duration"], inplace=True)

In [15]:
df.isnull().sum()

show_id           0
type              0
title             0
director        132
cast            204
country         466
date_added        0
release_year      0
rating            0
genres          107
language          0
description     132
popularity        0
vote_count        0
vote_average      0
budget            0
revenue           0
dtype: int64

In [17]:
duplicate_count = df.duplicated().sum()

print(f"Duplicate Rows: {duplicate_count}")

Duplicate Rows: 0

In [19]:
df.drop_duplicates(inplace=True)

print("New Shape:", df.shape)

New Shape: (16000, 17)

In [59]:
missing_values = df.isnull().sum()

missing_values[missing_values > 0]

director       132
cast           204
country        466
genres         107
description    132
dtype: int64

In [61]:
missing_summary = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": round(df.isnull().sum() / len(df) * 100, 2)
})

missing_summary[missing_summary["Missing Values"] > 0]

             Missing Values  Percentage
director                132        0.82
cast                    204        1.27
country                 466        2.91
genres                  107        0.67
description             132        0.82

In [63]:
df["date_added"].isnull().sum()

0

In [69]:
df = df.dropna(subset=["date_added"])

In [71]:
print("Missing Values:", df.isnull().sum().sum())

Missing Values: 1041

In [21]:
print(df.columns.duplicated().sum())

0

In [23]:
print(df.shape)
df.isnull().sum()
print("Duplicate Rows:", df.duplicated().sum())

(16000, 17)
Duplicate Rows: 0

In [25]:
df.select_dtypes(include="object").columns.tolist()

['type',
 'title',
 'director',
 'cast',
 'country',
 'date_added',
 'genres',
 'language',
 'description']

In [27]:
text_columns = df.select_dtypes(include="object").columns

for col in text_columns:
    df[col] = df[col].str.strip()

In [31]:
df["type"] = df["type"].str.title()
df["country"] = df["country"].str.title()
df["language"] = df["language"].str.lower()
print(df["type"].unique())

print(df["language"].value_counts().head())

['Movie']
language
en    9534
fr    1054
ja     904
ko     876
es     731
Name: count, dtype: int64

In [33]:
df["date_added"].dtype

dtype('O')

In [37]:
df["date_added"].dtype

dtype('<M8[ns]')

In [43]:
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
)

In [45]:
print(df.columns.tolist())

['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added', 'release_year', 'rating', 'genres', 'language', 'description', 'popularity', 'vote_count', 'vote_average', 'budget', 'revenue']

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16000 entries, 0 to 15999
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       16000 non-null  int64
 1   type          16000 non-null  object
 2   title         16000 non-null  object
 3   director      15868 non-null  object
 4   cast          15796 non-null  object
 5   country       15534 non-null  object
 6   date_added    16000 non-null  object
 7   release_year  16000 non-null  int64
 8   rating        16000 non-null  float64
 9   genres        15893 non-null  object
 10  language      16000 non-null  object
 11  description   15868 non-null  object
 12  popularity    16000 non-null  float64
 13  vote_count    16000 non-null  int64
 14  vote_average  16000 non-null  float64
 15  budget        16000 non-null  int64
 16  revenue       16000 non-null  int64
dtypes: float64(3), int64(5), object(9)
memory usage: 2.1+ MB

In [49]:
df["date_added"] = pd.to_datetime(
    df["date_added"],
    errors="coerce"
)

C:\Users\kandl\AppData\Local\Temp\ipykernel_3796\2883811207.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["date_added"] = pd.to_datetime(

In [51]:
print(df["date_added"].dtype)

datetime64[ns]

In [53]:
numeric_columns = [
    "release_year",
    "rating",
    "popularity",
    "vote_count",
    "vote_average",
    "budget",
    "revenue"
]

print(df[numeric_columns].dtypes)

release_year      int64
rating          float64
popularity      float64
vote_count        int64
vote_average    float64
budget            int64
revenue           int64
dtype: object

In [55]:
print("Dataset Shape:", df.shape)

print("\nMissing Values:")
print(df.isnull().sum().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nData Types:")
print(df.dtypes)

Dataset Shape: (16000, 17)

Missing Values:
1041

Duplicate Rows:
0

Data Types:
show_id                  int64
type                    object
title                   object
director                object
cast                    object
country                 object
date_added      datetime64[ns]
release_year             int64
rating                 float64
genres                  object
language                object
description             object
popularity             float64
vote_count               int64
vote_average           float64
budget                   int64
revenue                  int64
dtype: object

director       132
cast           204
country        466
genres         107
description    132
dtype: int64

In [75]:
# =========================
# Final Data Cleaning Pass
# =========================

# 1. Remove completely empty columns
empty_cols = df.columns[df.isnull().all()]
df.drop(columns=empty_cols, inplace=True)

# 2. Handle missing values in object columns
object_cols = df.select_dtypes(include="object").columns

for col in object_cols:
    df[col] = df[col].fillna("Unknown")

# 3. Handle missing values in numeric columns
numeric_cols = df.select_dtypes(include=["int64", "float64"]).columns

for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

# 4. Handle missing dates
if "date_added" in df.columns:
    df["date_added"] = pd.to_datetime(df["date_added"], errors="coerce")

    # Replace missing dates with most frequent date
    df["date_added"] = df["date_added"].fillna(
        df["date_added"].mode()[0]
    )

# 5. Remove duplicate rows
df.drop_duplicates(inplace=True)

# 6. Standardize text columns
for col in object_cols:
    df[col] = df[col].astype(str).str.strip()

# 7. Clean column names
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
)

# =========================
# Final Validation
# =========================

print("Dataset Shape:", df.shape)
print("Missing Values:", df.isnull().sum().sum())
print("Duplicate Rows:", df.duplicated().sum())

df.info()

Dataset Shape: (16000, 17)
Missing Values: 0
Duplicate Rows: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16000 entries, 0 to 15999
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       16000 non-null  int64
 1   type          16000 non-null  object
 2   title         16000 non-null  object
 3   director      16000 non-null  object
 4   cast          16000 non-null  object
 5   country       16000 non-null  object
 6   date_added    16000 non-null  datetime64[ns]
 7   release_year  16000 non-null  int64
 8   rating        16000 non-null  float64
 9   genres        16000 non-null  object
 10  language      16000 non-null  object
 11  description   16000 non-null  object
 12  popularity    16000 non-null  float64
 13  vote_count    16000 non-null  int64
 14  vote_average  16000 non-null  float64
 15  budget        16000 non-null  int64
 16  revenue       16000 non-null  int64
dtypes: datetime64[ns](1), float64(3), int64(5), object(8)
memory usage: 2.1+ MB

In [77]:
print("Dataset Shape:", df.shape)
print("Missing Values:", df.isnull().sum().sum())
print("Duplicate Rows:", df.duplicated().sum())

Dataset Shape: (16000, 17)
Missing Values: 0
Duplicate Rows: 0

In [79]:
df.to_csv("cleaned_netflix_movies_2025.csv", index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [81]:
import os

print(os.path.abspath("cleaned_netflix_movies_2025.csv"))

C:\Users\kandl\elavate labs\cleaned_netflix_movies_2025.csv